### PR TITLE
Default bar enhancements 

### PR DESCRIPTION
**Pull request by lasers**
Testing https://github.com/brndnmtthws/conky/pull/617

### CODE REVIEW

**Comment by su8** [comment]
Can you pull the latest changes sir ?

**Comment by lasers** [comment]
Broken `BAR1: ${execbar 30,50 "shuf -i 3-100 -n 1"}`

I think exclusive options in variables is bad. We forget about `x11`, `ncurses`, etc. Having to explain that it's only possible in `out_to_console` sucks... Better just to add `default_bar_fill` and `default_bar_unfill` and be done with it. *makes faces*

**Comment by su8** [comment]
Just made `${cpubar}` to work.

**Comment by lasers** [comment]
Join `##bars`.

**Comment by su8** [comment]
>Broken BAR1: ${execbar 30,50 "shuf -i 3-100 -n 1"}

It expects characters in the form of **X**,**0** e.g (`    ${execbar x,o "shuf -i 4-100 -n 1"}`) or `    ${execbar 30,100 #,_ "shuf -i 4-100 -n 1"}`

**Comment by lasers** [comment]
That is the current/default `execbar` behavior though. This would break existing users for no gain only because we want to support something exclusive/extra inside console.

Putting exclusive `ncurse` options in some variables, then exclusive `console` options for `execbar`, etc, will be hard to document and/or make documentation clear... in man page or others.

I personally think users won't use it very much since they're likely to want everything to be consistent... so that's why `default_bar_fill` and `default_bar_unfill` is sensible enough for console bars... and will just make everything consistent. I acknowledge it leads to slightly fewer bar choices.

**Comment by su8** [comment]
No we can't have characters inside `scan_bar()`, tried many combinations but it doesn't work.

**Comment by lasers** [comment]
Can you explain more? If this is for `default_bar_fill = 'example'`, then okay, I give it up. Use single characters instead. I just like `◼◼◼◼◼◼◼◽◽◽` more than `#####____`.

**Comment by su8** [comment]
>What do you mean... you made ${cpubar} work? It always works

With my commits cpubar and the rest wasn't working as the structure `bar` wasn't initialized.

Will try with string scanning approach to see whether it's working. As scanning %d **x** turns it into integer and never fails, so the rest `if` blocks are not entered.

**Comment by su8** [comment]
Even with limited **%3s%** string scanning always gets the first chars of `"shuf -i 4-100 -n 1"`, so no luck here too. Will close my PR right aways :sob:

**Comment by lasers** [comment]
:sob:

**Pull request closed without merging**
