### PR TITLE
Add new text objects to retrieve the currently used keyboard layout and mouse speed in percentage and generate random password of chosen length and get the cpu clock speed from assembly

### PR DESCRIPTION
**Pull request by su8**
~~Hey @brndnmtthws are you interested in getting the mouse speed in percentage ?~~

added it.

### CODE REVIEW

**Comment by lasers** [comment]
If you can, don't forget to document the new variables/objects. :heart: And to close old issues. :broken_heart:

**Comment by su8** [comment]
@brndnmtthws can you merge it to the master branch as well ?

**Comment by su8** [comment]
Or should I commit it again and open another PR ?

**Comment by brndnmtthws** [comment]
@su8 looks like something got messed up. Please open another PR.

**Pull request merged**
