### PR TITLE
Refactor mysql.cc

### PR DESCRIPTION
**Pull request by su8**

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Can you rebase this against master? For some reason it looks like Travis isn't picking up the changes to `.travis.yml`.

**Comment by su8** [comment]
I'm not sure how to rebase with git, can you provide me some command example ?

**Comment by brndnmtthws** [comment]
From your branch:
```
$ git pull https://github.com/brndnmtthws/conky.git master
$ git rebase master
```

**Comment by su8** [comment]
It says **Everything up-to-date**

**Comment by brndnmtthws** [comment]
I just realized those instructions are wrong because you're already on master. Do this:

```
$ git pull --rebase https://github.com/brndnmtthws/conky.git master
$ git push -f
```

**Comment by su8** [comment]
**net_stat.cc** is comparing array to null too (ns->addrs), can you change it to `ns->*addrs`:

```c
  if (nullptr != ns->addrs && strlen(ns->addrs) > 2) {
```

**Comment by brndnmtthws** [comment]
I cannot make changes to your branch. You'll have to fix the build before it can be merged.

**Comment by brndnmtthws** [comment]
I think the build is okay, but it seems sonar broke again (I think you might have accidentally dropped the changes). Can you rebase against master again?

**Pull request merged**
