### PR TITLE
Add Tests to test-common.cc

### PR DESCRIPTION
**Pull request by Tomunu**
Some of these Tests might be a little trivial or overkill, but hopefully it will make it easier to add more.

Fixes from the original failed pull request:
- Finish rename refactor
- Remove bad REQUIRE in Test and make behavior more consistent for a non-existent cpu
- Add the extern environ for Tests

### CODE REVIEW

**Comment by Tomunu** [comment]
Are the GitLab Pull and Build Failures real? If it has something to do with code changes (maybe the extern environ?) I can't see what the problem is. 
The Pull Failures are all:
```
fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/brndnmtthws-oss/conky.git/': Could not resolve host: gitlab.com
ERROR: Job failed: command terminated with exit code 1
```

**Comment by brndnmtthws** [comment]
@labhub-bot retry

**Comment by brndnmtthws** [comment]
> Are the GitLab Pull and Build Failures real? If it has something to do with code changes (maybe the extern environ?) I can't see what the problem is.
> The Pull Failures are all:
> 
> ```
> fatal: unable to access 'https://gitlab-ci-token:[MASKED]@gitlab.com/brndnmtthws-oss/conky.git/': Could not resolve host: gitlab.com
> ERROR: Job failed: command terminated with exit code 1
> ```

I see hostname resolution failures on gitlab all the time, and I don't know why it happens. I guess the local DNS server is overloaded for some reason. Usually retrying the build does the trick.

**Comment by brndnmtthws** [comment]
Thanks so much for doing this, it's really great work.

**Pull request merged**
