### PR TITLE
Fix for #691, nullptr deref.

### PR DESCRIPTION
**Pull request by brndnmtthws**

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Yeah I messed it up :) I'll update it in a moment.

**Comment by lasers** [comment]
Received signal SIGSEGV, Segmentation fault. It looks like same `bt full` output.

**Comment by brndnmtthws** [comment]
Hmm, still segfaulting in strndup? Let me test something out first.

**Comment by brndnmtthws** [comment]
Could you try compiling with debug symbols and then get a backtrace? Without line numbers it's a bit tricky.

**Comment by lasers** [comment]
I don't know this stuff at all. Can you be more explicit?

**Comment by brndnmtthws** [comment]
Just set the maintainer mode flag with cmake:

```
$ cmake .. -DMAINTAINER_MODE=ON
$ make
...
```

Then you should see the line numbers in the stack trace from gdb.

**Comment by lasers** [comment]
I used this (same as before). 
```
cmake -D CMAKE_BUILD_TYPE=Release -D MAINTAINER_MODE=ON ../
```
```gdb
Thread 14 "conky" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd77fe700 (LWP 12754)]
cat: /tmp/network_select_script/conky_data.txt: No such file or directory
0x00007ffff6638a26 in malloc () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff6638a26 in malloc () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff663c4ef in strndup () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00005555555bd3c5 in update_gateway_info() ()
No symbol table info available.
#3  0x00005555555b6664 in conky::priv::callback_base::start_routine() ()
No symbol table info available.
#4  0x00007ffff684f063 in std::execute_native_thread_routine (
    __p=0x5555556b1730)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = 0x5555556b1730}
#5  0x00007ffff7f75a9d in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#6  0x00007ffff66aeb23 in clone () from /usr/lib/libc.so.6
No symbol table info available.
(gdb)
```

**Comment by brndnmtthws** [comment]
Using both `CMAKE_BUILD_TYPE` and `MAINTAINER_MODE` will result in a build without debug symbols: https://github.com/brndnmtthws/conky/blob/master/cmake/ConkyBuildOptions.cmake#L22-L44

You need to either unset `CMAKE_BUILD_TYPE`, or set `CMAKE_BUILD_TYPE=Debug`.

**Comment by lasers** [comment]
Can't compile.
```
[ 37%] Building CXX object src/CMakeFiles/conky.dir/mboxscan.cc.o
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/conky.dir/build.make:154: src/CMakeFiles/conky.dir/diskio.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 39%] Building CXX object src/CMakeFiles/conky.dir/read_tcpip.cc.o
In file included from conky/src/conky.cc:88:
conky/src/diskio.h: In constructor ‘diskio_stat::diskio_stat()’:
conky/src/diskio.h:45:62: error: ‘memset’ used with length equal to number of elements without multiplication by element size [-Werror=memset-elt-size]
     std::memset(sample, 0, sizeof(sample) / sizeof(sample[0]));
                                                              ^
conky/src/diskio.h:46:77: error: ‘memset’ used with length equal to number of elements without multiplication by element size [-Werror=memset-elt-size]
     std::memset(sample_read, 0, sizeof(sample_read) / sizeof(sample_read[0]));
                                                                             ^
conky/src/diskio.h:48:63: error: ‘memset’ used with length equal to number of elements without multiplication by element size [-Werror=memset-elt-size]
                 sizeof(sample_write) / sizeof(sample_write[0]));
                                                               ^
conky/src/misc.cc: In function ‘void print_cap(text_object*, char*, unsigned int)’:
conky/src/misc.cc:100:22: error: ISO C++ forbids variable length array ‘buf’ [-Werror=vla]
   char buf[p_max_size];
                      ^
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/conky.dir/build.make:219: src/CMakeFiles/conky.dir/misc.cc.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/conky.dir/build.make:128: src/CMakeFiles/conky.dir/core.cc.o] Error 1
conky/src/net_stat.cc: In function ‘void free_dns_data(text_object*)’:
conky/src/net_stat.cc:558:40: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct _dns_data’; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(&dns_data, 0, sizeof(dns_data));
                                        ^
conky/src/net_stat.cc:543:8: note: ‘struct _dns_data’ declared here
 struct _dns_data {
        ^~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/conky.dir/build.make:232: src/CMakeFiles/conky.dir/net_stat.cc.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/conky.dir/build.make:115: src/CMakeFiles/conky.dir/conky.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:377: src/CMakeFiles/conky.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by brndnmtthws** [comment]
Hmm, I need to sort that out. In the meantime, just do:

```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
```

And it should compile with debug symbols.

**Comment by lasers** [comment]
Can't compile with `cmake -D CMAKE_BUILD_TYPE=Debug ../`.
```cmake
[ 83%] Building CXX object src/CMakeFiles/conky.dir/tcp-portmon.cc.o
conky/src/linux.cc: In function ‘int update_gateway_info()’:
conky/src/linux.cc:373:9: error: ‘SAVE_SET_STRING’ was not declared in this scope
         SAVE_SET_STRING(gw_info.iface, iface)
         ^~~~~~~~~~~~~~~
conky/src/linux.cc:373:9: note: suggested alternative: ‘LUA_TSTRING’
         SAVE_SET_STRING(gw_info.iface, iface)
         ^~~~~~~~~~~~~~~
         LUA_TSTRING
conky/src/users.cc: In function ‘void user_name(char*)’:
conky/src/users.cc:43:31: warning: ‘size_t strlen(const char*)’ argument 1 declared attribute ‘nonstring’ [-Wstringop-overflow=]
       if (strlen(ptr) + strlen(usr->ut_name) + 1 <= BUFLEN) {
                         ~~~~~~^~~~~~~~~~~~~~
In file included from /usr/include/features.h:428,
                 from /usr/include/time.h:25,
                 from conky/src/users.cc:30:
/usr/include/bits/utmp.h:66:5: note: argument ‘utmp::ut_user’ declared here
     __attribute_nonstring__; /* Username.  */
     ^~~~~~~~~~~~~~~~~~~~~~~
conky/src/users.cc: In function ‘void user_term(char*)’:
conky/src/users.cc:65:31: warning: ‘size_t strlen(const char*)’ argument 1 declared attribute ‘nonstring’ [-Wstringop-overflow=]
       if (strlen(ptr) + strlen(usr->ut_line) + 1 <= BUFLEN) {
                         ~~~~~~^~~~~~~~~~~~~~
In file included from /usr/include/features.h:428,
                 from /usr/include/time.h:25,
                 from conky/src/users.cc:30:
/usr/include/bits/utmp.h:63:5: note: argument ‘utmp::ut_line’ declared here
     __attribute_nonstring__; /* Devicename.  */
     ^~~~~~~~~~~~~~~~~~~~~~~
[ 85%] Building CXX object src/CMakeFiles/conky.dir/x11.cc.o
[ 86%] Building CXX object src/CMakeFiles/conky.dir/fonts.cc.o
[ 88%] Building CXX object src/CMakeFiles/conky.dir/hddtemp.cc.o
[ 90%] Building CXX object src/CMakeFiles/conky.dir/eve.cc.o
conky/src/linux.cc: In function ‘int open_sysfs_sensor(const char*, const char*, const char*, int, int*, char*)’:
conky/src/linux.cc:1136:14: warning: ‘char* strncat(char*, const char*, size_t)’ specified bound 256 equals destination size [-Wstringop-overflow=]
       strncat(buf, "/device", 256);
       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/conky.dir/build.make:505: src/CMakeFiles/conky.dir/linux.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:223: src/CMakeFiles/conky.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by brndnmtthws** [comment]
Yeah sorry. Forgot to commit part of the change. My bad.

**Comment by lasers** [comment]
```gdb
Thread 10 "conky" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffeddb1700 (LWP 24469)]
0x00007ffff65ead7f in raise () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff65ead7f in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff65d5672 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007ffff662d878 in __libc_message () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007ffff663418a in malloc_printerr () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x00007ffff6635b27 in _int_free () from /usr/lib/libc.so.6
No symbol table info available.
#5  0x000055555556f08f in free_and_zero<char> (ptr=@0x555555660778: 0x0) at /home/chris/src/conky/src/conky.h:356
No locals.
#6  0x00005555555c40d4 in update_gateway_info () at /home/chris/src/conky/src/linux.cc:361
        fp = 0x55555558f9b4 <std::_Tuple_impl<0ul, int (*)()>::_M_head(std::_Tuple_impl<0ul, int (*)()> const&)+24>
        ina = {s_addr = 16885952}
        iface = "\340\343\367\367\377\177\000\000\350\rmUUU\000\000\260\f\333\355\377\177\000\000\305\367XUUU\000\000\000\000\000\000\000\000\000\000\350\rmUUU\000\000\320\f\333\355\377\177\000\000\350\364XUUU\000"
        dest = 93824993791352
        gate = 93824993791464
        mask = 140737183943824
        flags = 1
#7  0x000055555558f34d in legacy_cb::work (this=0x5555556d0d70) at /home/chris/src/conky/src/text_object.h:82
No locals.
#8  0x00005555555c0565 in conky::priv::callback_base::start_routine (this=0x5555556d0d70) at /home/chris/src/conky/src/update-cb.cc:128
No locals.
#9  0x00005555555c1195 in std::__invoke_impl<void, void (conky::priv::callback_base::*)(), conky::priv::callback_base*> (
    __f=@0x55555571e620: (void (conky::priv::callback_base::*)(conky::priv::callback_base * const)) 0x5555555c0510 <conky::priv::callback_base::start_routine()>,
    __t=@0x55555571e618: 0x5555556d0d70) at /usr/include/c++/8.2.1/bits/invoke.h:73
No locals.
#10 0x00005555555c0c94 in std::__invoke<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> (
    __fn=@0x55555571e620: (void (conky::priv::callback_base::*)(conky::priv::callback_base * const)) 0x5555555c0510 <conky::priv::callback_base::start_routine()>,
    __args#0=@0x55555571e618: 0x5555556d0d70) at /usr/include/c++/8.2.1/bits/invoke.h:95
No locals.
#11 0x00005555555c3385 in std::thread::_Invoker<std::tuple<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> >::_M_invoke<0ul, 1ul> (this=0x55555571e618)
    at /usr/include/c++/8.2.1/thread:244
No locals.
#12 0x00005555555c3340 in std::thread::_Invoker<std::tuple<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> >::operator() (this=0x55555571e618)
    at /usr/include/c++/8.2.1/thread:253
No locals.
#13 0x00005555555c3324 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> > >::_M_run (this=0x55555571e610)
    at /usr/include/c++/8.2.1/thread:196
No locals.
#14 0x00007ffff684f063 in std::execute_native_thread_routine (__p=0x55555571e610) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = 0x55555571e610}
#15 0x00007ffff7f75a9d in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#16 0x00007ffff66aeb23 in clone () from /usr/lib/libc.so.6
No symbol table info available.
(gdb)
```

**Comment by brndnmtthws** [comment]
That's actually a different problem, but still a problem. That issue is caused by uninitialized memory. Give me a few minutes to sort this out.

**Comment by brndnmtthws** [comment]
Okay, the latest patch _should_ fix it, provided I didn't miss anything.

**Comment by lasers** [comment]
```
Thread 17 "conky" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd5ffb700 (LWP 32119)]
cat: /tmp/network_select_script/conky_data.txtcat: /tmp/network_select_script/conky_data.txt: No such file or directory
: No such file or directory
cat: /tmp/network_select_script/conky_data.txt: No such file or directory
0x00007ffff6638a26 in malloc () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007ffff6638a26 in malloc () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff663c4ef in strndup () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00005555555c3d38 in save_set_string (x=0x0, y=0x7fffd5ffaa50 "eno1")
    at conky/src/linux.cc:285
No locals.
#3  0x00005555555c41e0 in update_gateway_info ()
    at conky/src/linux.cc:377
        fp = 0x7fffac000b20
        ina = {s_addr = 3590305536}
        iface = "eno1\000\000\000\000 \v\000\254\377\177", '\000' <repeats 11 times>, "\341v\366\377\177\000\000\317\332\377\377\377\177\000\000\000\267\377\325\377\177\000\000\000\000\000\000\000\000\000\000\006\071b\366\377\177\000"
        dest = 0
        gate = 16885952
        mask = 0
        flags = 3
#4  0x00005555555c4522 in update_net_stats ()
    at conky/src/linux.cc:449
        net_dev_fp = 0x7fffac000b20
        rep = 0
        first = 0 '\000'
--Type <RET> for more, q to quit, c to continue without paging--c
        i = 1
        i2 = 2
        curtmp1 = 1266
        curtmp2 = 673
        k = 2
        conf = {ifc_len = 80, ifc_ifcu = {ifcu_buf = 0x7fffac001840 "lo", ifcu_req = 0x7fffac001840}}
        buf = "  eno1\000 7022106241 4948517    0   32    0     0          0      8540 222557594 2324411    0    0    0     0       0          0\n", '\000' <repeats 25 times>, "F\344\367\367\377\177", '\000' <repeats 18 times>, "\310\003tUUU\000\000\070\004tUUU\000\000\220\254\377\325\377\177\000\000"...
        delta = 1.5012119339953642
        one = 0x7fffd5ffabb0 "  eno1"
        two = 0x7fffd5ffabb0 "  eno1"
        file = 0x7fffac001180
        v6addr = "fe8", '0' <repeats 13 times>, "b43bb00d6546500c"
        devname = "eno1", '\000' <repeats 16 times>
        netmask = 64
        scope = 32
        ns = 0x5555556453c0 <netstats>
        lastv6 = 0x7fffac0017f0
#5  0x000055555558f34d in legacy_cb::work (this=0x5555557403c0) at conky/src/text_object.h:82
No locals.
#6  0x00005555555c0565 in conky::priv::callback_base::start_routine (this=0x5555557403c0) at conky/src/update-cb.cc:128
No locals.
#7  0x00005555555c1195 in std::__invoke_impl<void, void (conky::priv::callback_base::*)(), conky::priv::callback_base*> (__f=@0x555555767730: (void (conky::priv::callback_base::*)(conky::priv::callback_base * const)) 0x5555555c0510 <conky::priv::callback_base::start_routine()>, __t=@0x555555767728: 0x5555557403c0) at /usr/include/c++/8.2.1/bits/invoke.h:73
No locals.
#8  0x00005555555c0c94 in std::__invoke<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> (__fn=@0x555555767730: (void (conky::priv::callback_base::*)(conky::priv::callback_base * const)) 0x5555555c0510 <conky::priv::callback_base::start_routine()>, __args#0=@0x555555767728: 0x5555557403c0) at /usr/include/c++/8.2.1/bits/invoke.h:95
No locals.
#9  0x00005555555c3385 in std::thread::_Invoker<std::tuple<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> >::_M_invoke<0ul, 1ul> (this=0x555555767728) at /usr/include/c++/8.2.1/thread:244
No locals.
#10 0x00005555555c3340 in std::thread::_Invoker<std::tuple<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> >::operator() (this=0x555555767728) at /usr/include/c++/8.2.1/thread:253
No locals.
#11 0x00005555555c3324 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (conky::priv::callback_base::*)(), conky::priv::callback_base*> > >::_M_run (this=0x555555767720) at /usr/include/c++/8.2.1/thread:196
No locals.
#12 0x00007ffff684f063 in std::execute_native_thread_routine (__p=0x555555767720) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = 0x555555767720}
#13 0x00007ffff7f75a9d in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#14 0x00007ffff66aeb23 in clone () from /usr/lib/libc.so.6
No symbol table info available.
(gdb)
```

**Comment by lasers** [comment]
Do you need `bt full` output from the latest commit? Going to get something to eat.

**Comment by brndnmtthws** [comment]
I'm still not sure why that's happening. I can't reproduce it, and the stack trace doesn't hint as to why it's blowing up.

**Comment by lasers** [comment]
I'm not sure what's going on, but this is the first network line that starts throwing a segfault.
```
${goto 6}${voffset 1}${font conkycolors:size=14}x${font}${goto 32}${voffset -5}Upspeed: ${alignr}${eval $${upspeedf ${execi 1 (ip route | grep default.* | grep -Po '(?<=dev\s)\w+' | head -1)}}}${font} KiB/s
```
If I added `${upspeedf eno1}` before that line, it throws a segfault too. I tried having `${upspeedf eno1}` alone in the config and it does not throw an error.

I think you should look into `${upspeedf}/${downspeedf}` and see if anything turns up.

**Comment by brndnmtthws** [comment]
Right now I think the issue might be related to fonts. I need to keep debugging.

**Pull request merged**
