### PR TITLE
changed the base image to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by tallhypnosis**
# Checklist
- [x] I have described the changes
- [x] I have linked to any relevant GitHub issues, if applicable
- [x] Documentation in `doc/` has been updated
- [x] All new code is licensed under GPLv3

## Description

* Describe the changes, why they were necessary, etc
* Describe how the changes will affect existing behaviour.
* Describe how you tested and validated your changes.
* Include any relevant screenshots/evidence demonstrating that the changes work and have been tested.

### CODE REVIEW

**Comment by tallhypnosis** [comment]
changed the base image

**Comment by brndnmtthws** [comment]
I appreciate the PR, but I'm going to stick with the current release.

**Comment by tallhypnosis** [comment]
@brndnmtthws  fine by my side

**Comment by tallhypnosis** [comment]
@brndnmtthws  could you please help me with me with contributions as i am quiet a novice in open source.

**Pull request closed without merging**
