### PR TITLE
respect LIB_INSTALL_DIR

### PR DESCRIPTION
**Pull request by marguerite**
many other cmake projects use this flag too. and some distros have this preset.

### CODE REVIEW

**Comment by chepioq** [comment]
I agree with that, I use Fedora and libs are not installed in /usr/local/lib but in /usr/lib or usr/lib64 .
I rebuild the rpm with your commit and that work fine, and now I'm not obliged to make a link in /usr/local/

**Comment by marguerite** [comment]
@chepioq actually it's the patch I use to maintain conky for openSUSE :-)

**Comment by chepioq** [comment]
Please, do you push this commit in master branch, it's very important for maintainer of many distro (the maintainer for fedora need that commits are in the master's branch to add this in the rpm).

**Comment by brndnmtthws** [comment]
Thanks.

**Pull request merged**
