### PR TITLE
CMake fixes

### PR DESCRIPTION
**Pull request by mlichvar**
The following modifications of the cmake files seem to be needed to compile conky and install correctly on Fedora.

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Looks like the build is failing. Can you take another look?

**Comment by mlichvar** [comment]
Oh, it looks like we need to include both CheckIncludeFile and CheckIncludeFiles. Should be fixed now.

**Comment by cwebster2** [comment]
CheckIncludeFile doesn't exist on my system (and apparently others with newer versions of cmake).  See my PR for Issue #162 that gets rid of the need for CheckIncludeFile in favor of CheckIncludeFiles.

**Comment by brndnmtthws** [comment]
Can you rebase again on master?

**Comment by mlichvar** [comment]
The remaining patch is now rebased. Thanks.

**Pull request merged**
