### PR TITLE
Delete broken weathervars before rewrite

### PR DESCRIPTION
**Pull request by ngaro**
${weather} and ${weather_forecast} are still broken.
Before rewriting them it might be a good idea to remove them in a combination of a small amount of large commits.
That way it should be easier to find ideas from the old cold to use in the new code.

### CODE REVIEW

**Comment by lasers** [comment]
```
${weather http://tgftp.nws.noaa.gov/data/observations/metar/stations/ xxxx temperature}
```
... works okay here for me. Replace `xxxx` with https://www.airnav.com/airports/

**Comment by lasers** [comment]
```
conky.config = {
    out_to_x=false,
    out_to_console=true,
}
conky.text = [[${weather http://tgftp.nws.noaa.gov/data/observations/metar/stations/ EBAW temperature}]]
```
```
0
0
17
17
```

**Comment by lasers** [comment]
If conky is printing `0`, then it's misleading on conky's part. It should just not print anything instead.

**Comment by ngaro** [comment]
Indeed, you'll never even see 17 but only the incorrect 0(-s) when you use "-i1" or "-i2" as option when running conky.

**Comment by lasers** [comment]
If you can find out why it is printing `0` for first or second time instead of fetching... then you can try and correct this behavior. Other variables will benefit from this change. Users too.

**Comment by brndnmtthws** [comment]
Do you want to get this in before I cut a release?

**Pull request merged**
