### PR TITLE
Linux: show the CPU scaling governor with $cpugovernor

### PR DESCRIPTION
**Pull request by pghvlaans**
**Descriptions**
* For Linux, display the CPU scaling governor for any thread with a variable `$cpugovernor`. This will help users who change their scaling governors on the fly to keep track of what they're doing.
* No existing behavior is changed.
* I tested `$cpugovernor` with various combinations of CPU scheduling governors, as well as the default value (`cpu0`) and invalid values (which revert to the default).
* Screenshot: 
cpugovernors

**Licenses**
* There are no new files.

### CODE REVIEW

**Comment by su8** [comment]
`atoi` can introduce undefined behaviour to conky, replace it with `strtol`

**Comment by pghvlaans** [comment]
It works with `strtol`. Everything else in `core.cc` uses `atoi`, though.

**Comment by brndnmtthws** [comment]
> It works with `strtol`. Everything else in `core.cc` uses `atoi`, though.

I understand there's a lot of existing crufty bits in the code, but if you're adding new code it's preferred to use C functions that (at a minimum) reduce the possibility of bugs such as reading past the end of buffers.

**Comment by pghvlaans** [comment]
OK, understood! I'll go ahead and push.

**Review by brndnmtthws — APPROVED** [review]
This is great, thank you kindly.

**Pull request merged**
