### PR TITLE
Increase default number of net interfaces.

### PR DESCRIPTION
**Pull request by brndnmtthws**
This should resolve the issue noted in #564.

### CODE REVIEW

**Comment by lasers** [comment]
linuix.cc / Line 106 needs this too?
```
src/linux.cc:106:char interfaces_arr[iface_len][iface_len] = {""};
src/linux.cc:355:        snprintf(interfaces_arr[x++], iface_len - 1, "%s", iface);
src/linux.cc:357:      } else if (0 == strcmp(iface, interfaces_arr[x - 1])) {
src/linux.cc:361:        strcmpreturn = strcmp(iface, interfaces_arr[z]);
src/linux.cc:364:        snprintf(interfaces_arr[x++], iface_len - 1, "%s", iface);
src/linux.cc:430:      if (0 == strcmp("", interfaces_arr[x])) { break; }
src/linux.cc:431:      buf_ptr += snprintf(buf_ptr, iface_len - 1, "%s, ", interfaces_arr[x]);
src/linux.cc:443:  if ((iface_len - 1) > z) { snprintf(p, p_max_size, "%s", interfaces_arr[z]); }
src/linux.h:63:extern char interfaces_arr[64][64];
src/net_stat.cc:57:static char interfaces_arr[64][64] = {""};
src/net_stat.cc:152:      if (63L > x) { arg = interfaces_arr[x]; }
```

**Comment by brndnmtthws** [comment]
Good catch, thanks.

**Comment by lasers** [comment]
(Q) `static const unsigned int iface_len = 64U` is okay?

This branch ran fine here. That's about as far as I tested.

**Comment by brndnmtthws** [comment]
> (Q) `static const unsigned int iface_len = 64U` is okay?
> 
> This branch ran fine here. That's about as far as I tested.
> 
> EDIT: Also `conky -V` prints `Maximum netdevices: 256` ok.

It's confusing, but, the 2nd arg to that array is the length of the string in the arr (it's an array of iface names, so eth0, eth1, eth2, ...).

It would be better to fix it properly, but I don't want to change all the code and introduce any regressions :)

**Comment by brndnmtthws** [comment]
@labhub-bot retry

**Pull request merged**
