### PR TITLE
Haiku port phase 1

### PR DESCRIPTION
**Pull request by mmuman**
This implements basic support for the Haiku Operating System, using ncurses.

It compiles and gets the default view mostly working in the Terminal.

### CODE REVIEW

**Comment by brndnmtthws** [comment]
Would you mind rebasing and testing again?

**Comment by mmuman** [comment]
Aw, let's hope it won't clash too much with the solaris stuff…

**Comment by brndnmtthws** [comment]
Yeah, sorry about that.

**Comment by mmuman** [comment]
There you go, still building fine.
I think some headers should rather be AC_CHECKed for instead of testing 4 or 5 defines, I might try to clean that someday.

**Pull request merged**
