### PR TITLE
Add Tests in new Test files

### PR DESCRIPTION
**Pull request by Tomunu**
I added only a few Tests in each of these areas. There are a lot more that would be easy to add there and in other areas, but I wanted this to be a clean example of how to add new Test files, including Tests that depend on build flags. 

Some of the areas that I didn't touch are printing/output and initialization.

### CODE REVIEW

**Comment by lasers** [comment]
@labhub-bot retry you pos

**Comment by Tomunu** [comment]
Haha! Every time.

**Comment by lasers** [comment]
`SECTION("for missing data") { REQUIRE(diskiographval(&obj) == 0.0); }` ?

**Comment by Tomunu** [comment]
It's testing that, if there's no `diskio_stat` data contained in the `text_object`, then `diskiographval` returns 0. 
But the test is failing with the expansion of the REQUIRE `0.0 == Approx( 0.0 )`? 

And the OSX builds are also failing on `fs_free_percentage returns correct value`. It doesn't say why or which section, but I'm guessing it's for the same thing.

**Comment by Tomunu** [comment]
Looks like a problem with comparing floating point zero using the default Approx in Catch2. 
I'll try that change and see if it fixes it.

**Comment by Tomunu** [comment]
It looks like it was just the Tests for missing data that were having the problem, so I've removed them for now. Maybe I'll add them back later. 

But this is the last I'll be working on the Tests for a while. I'll look into other Issues instead.

**Pull request merged**
