### PR TITLE
Add toluapp subtree

### PR DESCRIPTION
**Pull request by brndnmtthws**

### CODE REVIEW

**Comment by brndnmtthws** [comment]
If someone other than me could test this, that would be good 😄

**Comment by plikhari** [comment]
OK kewl - testing testing ;-))

**Comment by lasers** [comment]
@plikhari Both comments indicates you tried this on `master` branch.

**Comment by lasers** [comment]
Depending on what your `git remote -v` looks like... You want to try one of the commands.
* `git checkout upstream/add-toluapp-subtree`
--OR--
* `git checkout brndnmtthws/add-toluapp-subtree`

**Comment by plikhari** [comment]
For some reason this does not seem to work (subtree thing)
The branch looks fine.
Perhaps later in the evening I shall look at it - as I have to run out now.

**Comment by npyl** [comment]
@brndnmtthws  I have successfully compiled this PR on macOS but how do I actually test it?

**Comment by brndnmtthws** [comment]
To fetch the branch you can run:

```ShellSession
$ git clone https://github.com/brndnmtthws/conky.git
$ cd conky
$ git fetch origin
$ git checkout -b add-toluapp-subtree origin/add-toluapp-subtree
$ git merge master
```

@npyl just need to run something that uses the Lua bindings. You can try the Cairo stuff from here: https://github.com/brndnmtthws/conky/wiki/Using-Lua-scripts-in-conky-(Part-01):-How-does-a-lua-script-work

**Comment by npyl** [comment]
@brndnmtthws I think i have good news! :) (I have disabled the cairo stuff because I haven't found a way to install it on macOS but I think LUA is working because functions such as `tonumber` seem to work, etc, etc...)

screenshot 2018-12-20 at 17 52 28

**Comment by brndnmtthws** [comment]
@npyl it should work on macos (cairo + xlib), but I haven't tried it yet. Let me see if I can get it working.

**Comment by brndnmtthws** [comment]
@npyl I compiled cairo from source, and it works fine.

Here's the lua file I used:

```lua
package.cpath = package.cpath .. ";lua/lib?.dylib"
require 'cairo'

function conky_main()
    if conky_window == nil then
        return
    end
    local cs = cairo_xlib_surface_create(conky_window.display,
                                         conky_window.drawable,
                                         conky_window.visual,
                                         conky_window.width,
                                         conky_window.height)
    local updates=tonumber(conky_parse('${updates}'))
    if updates>5 then
        print ("hello world")
    end
    cr = cairo_create(cs)
    cairo_set_line_width(cr, 5.0)
    cairo_move_to(cr, 0.0, 0.0)
    cairo_line_to(cr, conky_window.width, conky_window.height)
    cairo_set_source_rgba(cr, 1, 0.2, 0.2, 0.6)
    cairo_stroke(cr)
    cairo_destroy(cr)
    cairo_surface_destroy(cs)
end
```
Conky config:
```
conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 5,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false,
    lua_load = "./lol.lua",
    lua_draw_hook_post = "main",
}

conky.text = [[
${scroll 16 $nodename - $sysname $kernel on $machine | }
$hr
${color grey}Uptime:$color $uptime
${color grey}Frequency (in MHz):$color $freq
${color grey}Frequency (in GHz):$color $freq_g
${color grey}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color grey}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}
${color grey}CPU Usage:$color $cpu% ${cpubar 4}
${color grey}Processes:$color $processes  ${color grey}Running:$color $running_processes
$hr
${color grey}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color grey}Networking:
Up:$color ${upspeed} ${color grey} - Down:$color ${downspeed}
$hr
${color grey}Name              PID   CPU%   MEM%
${color lightgrey} ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
${color lightgrey} ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
${color lightgrey} ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
${color lightgrey} ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
]]
```
Result:
screen shot 2018-12-20 at 3 16 17 pm

**Comment by npyl** [comment]
@brndnmtthws I have installed cairo with homebrew but I think we need something like [this](https://github.com/awesomeWM/oocairo).  Can you please tell me how you did it?

**Comment by npyl** [comment]
@brndnmtthws Can you please tell me how you did it? I just built cairo from source and it didn't work!

Did you build [this?](https://github.com/awesomeWM/oocairo)

**Comment by npyl** [comment]
@brndnmtthws It worked for me, too!  Thank you for your help!

**Pull request merged**
