### PR TITLE
Fix goto in ncurses mode when compiled without BUILD_X11

### PR DESCRIPTION
**Pull request by lasers**
Testing #680. See if I can merge something without an approval from anybody else.

### CODE REVIEW

**Comment by lasers** [comment]
@livanh 4 open issues. Fixable?

**Comment by livanh** [comment]
Is there something else I can do here? As I wrote in #680, one issue is about using `union` but I don't see a way to avoid it. The other one is about replacing a `free` in conky.h, but for this we should first replace many more `malloc`s in other files (perhaps all of them).

**Comment by lasers** [comment]
You're probably okay here. We _Collaborators_ can't merge anything with failed tests. We need to wait for @brndnmtthws _Owner_ to come back and decide what to do with this and many other PRs. He said things have been busy for him recently so maybe in a week or two.

The alternative is to resolving open issues with the files you made changes on.
* https://rules.sonarsource.com/c/RSPEC-953
* https://rules.sonarsource.com/cpp/tag/leak/RSPEC-1231

If you want to change all `mallocs` in other files, you likely will have to deal with unrelated open issues too. Owner added `SonarCloud` not long ago and the scope is set up to focus on changed files only so we are dealing with each changed files one. We need more contributors too. :-)

**Comment by brndnmtthws** [comment]
Closing this in favour of #680.

**Pull request closed without merging**
