### PR TITLE
Wayland GUI backend

### LINKED ISSUE #56: Any plan for wayland?
Is it possible to add support for wayland?

### PR DESCRIPTION
**Pull request by bi4k8**
# Checklist
- [x] I have described the changes
- [x] I have linked to any relevant GitHub issues, if applicable
- [x] Documentation in `doc/` has been updated
- [x] All new code is licensed under GPLv3

## Description

I have an old (last April) branch implementing a Wayland backend that I've finally fixed to not break X11 anymore. This needs lots of cleanups, but I wanted to get a PR open so people can test and I can get feedback.

Fixes #56.

~This probably needs a huge rebase at this point.~ Rebased.

I've tested it under labwc and sway, but not other compositors. It uses Cairo for all rendering and the `wlr-layer-shell-unstable-v1` protocol to place its window appropriately. This moves a relatively large amount of code from X11 files to shared GUI ones. It adds a `out_to_wayland` configuration setting; setting `out_to_wayland = true` should be all that's needed to test an existing config.

### CODE REVIEW

**Comment by bi4k8** [comment]
I'll clean up a lot of the smaller tweak commits. For example,
- `HACK: remove sleep(1) on config reload` doesn't need to be there
- `bonus flush`, `remove resizing print`, `remove unused wl_shell binding`, and a number of others will get squashed

and a bunch more.

That said, I'd like particular attention on these commits:
- `fix segfault when no display outputs are enabled` (is this a sane fix?)
- `fix misbehavior in specials handling that fails badly with Wayland ba…` (the code here seemed wrong, but it isn't clear why it would behave worse with Wayland than X11)
- `fix right-alignment with wayland` (I don't understand why this works, nor why it was initially broken on Wayland compared to X11)

**Comment by bi4k8** [comment]
Cleaned everything up substantially. I think this is now in a reviewable state.

**Comment by mmuman** [comment]
I guess I'll have to have a try at a Wayland session soon :-)

You may want to use clang-format over the source files.

**Comment by mmuman** [comment]
Not sure there's a need to have a separate `wl.cc` file. I left the `x11.cc` because I didn't want to touch too much of it, but possibly it could be merged someday.

**Comment by brndnmtthws** [comment]
Can you rebase on top of #1250 (or wait for it to get merged)? I want to make sure these don't conflict.

**Comment by bi4k8** [comment]
> Can you rebase on top of #1250 (or wait for it to get merged)? I want to make sure these don't conflict.

Sure. I'll wait for #1250 to merge first so I'm not rebasing onto a moving target.

**Comment by bi4k8** [comment]
Tests are now green.

**Review by brndnmtthws — APPROVED** [review]

**Comment by brndnmtthws** [comment]
This is a big change, and there's a decent chance things will break, but I think we can ship it just in time for Xmas (if that's something you care about) 🙂

Thanks for the PR, this is great!

**Comment by brndnmtthws** [comment]
I merged this manually: https://github.com/brndnmtthws/conky/commit/cf16110c7a9f7362cd4f0bbe8c348cffd06a206b

**Comment by stacyharper** [comment]
I tried to compile master and got this:

```
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):                                                              
  The package name passed to `find_package_handle_standard_args`                                                                                                
  (WAYLAND_CLIENT) does not match the name of the calling package (Wayland).                                                                                    
  This can lead to problems in calling code that expects `find_package`                                                                                         
  result variables (e.g., `_FOUND`) to follow a certain pattern.                                                                                                
Call Stack (most recent call first):                                                                                                                            
  cmake/FindWayland.cmake:44 (find_package_handle_standard_args)                                                                                                
  cmake/ConkyPlatformChecks.cmake:356 (find_package)                                                                                                            
  CMakeLists.txt:35 (include)                                                                                                                                   
This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                           
                                                                                                                                                                
```

and then some issues while building. If it can help debuging.

Dear santa is lovely this year \o/

**Comment by brndnmtthws** [comment]
> I tried to compile master and got this:
> 
> ```
> CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):                                                              
>   The package name passed to `find_package_handle_standard_args`                                                                                                
>   (WAYLAND_CLIENT) does not match the name of the calling package (Wayland).                                                                                    
>   This can lead to problems in calling code that expects `find_package`                                                                                         
>   result variables (e.g., `_FOUND`) to follow a certain pattern.                                                                                                
> Call Stack (most recent call first):                                                                                                                            
>   cmake/FindWayland.cmake:44 (find_package_handle_standard_args)                                                                                                
>   cmake/ConkyPlatformChecks.cmake:356 (find_package)                                                                                                            
>   CMakeLists.txt:35 (include)                                                                                                                                   
> This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                           
>                                                                                                                                                                 
> ```
> 
> and then some issues while building. If it can help debuging. It is from Alpine Linux
> 
> Dear santa is lovely this year \o/

I'm in the process of fixing that, check back in a little while :)

**Comment by stacyharper** [comment]
Mah, I still got problems with BUILD_WAYLAND=ON

```
ninja: job failed: /usr/bin/g++ -D_LARGEFILE64_SOURCE -D_POSIX_C_SOURCE=200809L -I/home/willow/sources/aports/main/conky/src/conky-1.16.0/3rdparty/toluapp/inclu
de -I/home/willow/sources/aports/main/conky/src/conky-1.16.0/build -I/usr/include/freetype2 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0
/include -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include
/pixman-1 -I/usr/include/lua5.3 -I/usr/include/libxml2 -I/home/willow/sources/aports/main/conky/src/conky-1.16.0/build/data -I/home/willow/sources/aports/main/c
onky/src/conky-1.16.0/build/src -Os -fomit-frame-pointer -Os -DNDEBUG -std=c++17 -MD -MT src/CMakeFiles/conky.dir/display-wayland.cc.o -MF src/CMakeFiles/conky.
dir/display-wayland.cc.o.d -o src/CMakeFiles/conky.dir/display-wayland.cc.o -c /home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc   
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc: In function 'int set_cloexec_or_close(int)':                                    
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc:80:3: error: 'close' was not declared in this scope; did you mean 'pclose'?      
   80 |   close(fd);                                                                                                                                            
      |   ^~~~~
      |   pclose
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc: In function 'int create_tmpfile_cloexec(char*)':
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc:94:5: error: 'unlink' was not declared in this scope; did you mean 'inline'?
   94 |     unlink(tmpname);
      |     ^~~~~~
      |     inline
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc: In function 'int os_create_anonymous_file(off_t)':
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc:148:5: error: 'close' was not declared in this scope; did you mean 'pclose'?
  148 |     close(fd);
      |     ^~~~~
      |     pclose
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc: In function 'wl_shm_pool* conky::make_shm_pool(wl_shm*, int, void**)':
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc:943:5: error: 'close' was not declared in this scope; did you mean 'pclose'?
  943 |     close(fd);
      |     ^~~~~
      |     pclose
/home/willow/sources/aports/main/conky/src/conky-1.16.0/src/display-wayland.cc:949:3: error: 'close' was not declared in this scope; did you mean 'pclose'?
  949 |   close(fd);
      |   ^~~~~
      |   pclose
ninja: subcommand failed
```

**Comment by brndnmtthws** [comment]
> 

That's insanely annoying. Can you try https://github.com/brndnmtthws/conky/pull/1337?

**Comment by stacyharper** [comment]
Yes with this it compile ! And it works !

**Comment by mmuman** [comment]
Cool, we might get some PR from some youtuber soon now :-D

Just a few things I noted when I started reviewing:
The cURL check is now twice in  `cmake/ConkyPlatformChecks.cmake`.
The asserts have been commented in `src/fonts.cc` and I'm not sure we want this.

**Comment by brndnmtthws** [comment]
> 

I think a lot of things broke with this PR, unfortunately. I should have tested better :)

I'm trying to figure out what caused the breakage, but a lot shifted around so it's not easy to debug.

**Comment by saltasatelites** [comment]
Have you taken a look to nwg-wrapper? Maybe could help; allows show text on the screen and show some text too.

**Pull request closed without merging**
