### PR TITLE
Add ${battery_status} variable to display the battery status

### PR DESCRIPTION
**Pull request by su8**
**DO NOT MERGER UNLESS @lasers says THAT IT'S WORKING**

**EDIT: @lasers HERE. IT'S WORKING. @su8 FORGET TO REF https://github.com/brndnmtthws/conky/issues/191:+1**

### CODE REVIEW

**Comment by su8** [comment]
Did you used `${battery_status BAT0}` ?

**Comment by lasers** [comment]
I used `${battery_status}` just like other placeholders. `${battery_status BAT0}` works.

**Comment by lasers** [comment]
Pass it as-is... (lowercase). We should implement your pascal case func, lower case func, upper case func, etc. `${battery_status}` should default to `${battery_status BAT0}` too.

**Comment by lasers** [comment]
:warning: This PR is outdated. Your urgent attention to this matter would be appreciated. :sleeping:

**Comment by lasers** [comment]
@su8 Can you `git pull --rebase` and fix the conflicts?

**Comment by lasers** [comment]
The tests failed again.

**Pull request merged**
