### PR TITLE
Better BUILD_GUI and BUILD_* isolation

### PR DESCRIPTION
**Pull request by npyl**
This will break macOS compilation but will allow testing on Linux (can't do on my computer) and will show us some hints on what to isolate and where.

### CODE REVIEW

**Comment by npyl** [comment]
Oh right! I need to create a new PR for my PR. :/

**Comment by lasers** [comment]
Works for me on Linux.

**Comment by npyl** [comment]
> Works for me okay on Linux.

How??? :D The tests failed even for linux

**Comment by lasers** [comment]
From what I kept seeing, the tests sometimes fail in that same place.
```
The command "if [ "$CXX" = "clang++-6.0" ] ; then build-wrapper-linux-x86-64 --out-dir bw-output make -j4 ; fi" exited with 127.
```
It's often that place or no token (due to non-upstream PR). If fail, try again as it _could_ work okay on next run or two (must have a different hash to trigger a new run).

>Maybe you are compiling without BUILD_GUI set to ON?

`cmake -D CMAKE_BUILD_TYPE=Release -D MAINTAINER_MODE=ON -D BUILD_GUI=ON` :heavy_check_mark: 
`cmake -D CMAKE_BUILD_TYPE=Release -D MAINTAINER_MODE=ON -D BUILD_GUI=OFF` :heavy_multiplication_x:

**Comment by lasers** [comment]
@npyl Is it possible to fix (2) CodeFactor errors?

**Comment by npyl** [comment]
> @npyl Is it possible to fix (2) CodeFactor errors? EDIT: Got new errors for you.

Sure I will look it up! :)

**Comment by npyl** [comment]
Ok, @mmuman this PR aims at handling `BUILD_GUI` and `BUILD_X11` / `BUILD_METAL` in a better way than what we used to.  This is the scheme:

1. have BUILD_GUI as a user selectable option
2. if OS_DARWIN and BUILD_GUI enable BUILD_METAL
    else if another OS and BUILD_GUI enable BUILD_X11

This can be seen in the changes in `ConkyBuildOptions.cmake`.
I don't know if you would be interested in this as A) you may already have it done locally :)
B) exposes alot stuff that are not yet isolated such as fonts. (the biggest problem i think)

I am probably going to keep this PR here because I am planning to disable some font-stuff to start experimenting with Metal locally :)

**Comment by npyl** [comment]
Also, I realised that some things from the priv namespace probably need to be moved from `x11.h` to `display-output.hh`

**Comment by mmuman** [comment]
I'm getting a bit lost with everyone copying things around :D

**Comment by npyl** [comment]
>I'm getting a bit lost with everyone copying things around :D
> I too am eager to get the Haiku GUI code working, but I'd rather do things in order.

I figured man.  I just thought this would probably help you because right now, locally I have moved some structs from `x11.h` to `display-outputs.hh` because they should be public.  Would you like me to continue this or handle it by yourself? Whatever you like :)

> Also, I don't see why we wouldn't allow X11 build on OSX, even if not enabled by efault.
> like if(OS_DARWIN or …) default to false.

I agree! That's better than using only one thing on every OS...

> I theory it's even possible to support both and have the GUI selected at runtime.
> We'll also have to decide how we deal with rc files, since requiring people to edit them to change "x11" with something else is not ideal.

If the user hasn't explicitly specified which GUI he wants to use we could use the one more native / new / prefered / (whatever) as default and provide an option like `gui = 'x11'`

**Comment by mmuman** [comment]
Oh, has all this been merged already ? Been busy elsewhere… How much is left to merge from what I did initially? Do I have to rebase anything ?

**Comment by npyl** [comment]
Hey @mmuman 
sorry for the inconvenience.

Actually no, this has not been merged.
I just closed this PR because it was a branch based on yours and a patch of mine.

It was more confusing than helpful and I decided to close it.
You may have to rebase and fix some conflicts in order to continue your work.

Thanks for the great work

**Pull request closed without merging**
