### PR TITLE
Build AppImage separately per OS

### PR DESCRIPTION
**Pull request by stdedos**
Different OS'es have different `GLIBC_X.XX` versions.

While installing extra libraries is of course maybe necessary, it is next-to-impossible (AFAIU) to install/compliment a diffent `GLIBC_X.XX` on non-flexible OSes such as Debian, Ubuntu, etc.

If AppImage is unable to hide those differences,
then we must diversify if we want to support a wider base.

Fixes: https://github.com/brndnmtthws/conky/issues/1142
Fixes: https://github.com/brndnmtthws/conky/issues/1717

... and probably others.

# Checklist
- [x] I have described the changes
- [x] I have linked to any relevant GitHub issues, if applicable
- [ ] ~Documentation in `doc/` has been updated~
- [x] All new code is licensed under GPLv3

## Description

* Describe the changes, why they were necessary, etc
* Describe how the changes will affect existing behaviour.
* Describe how you tested and validated your changes.
* Include any relevant screenshots/evidence demonstrating that the changes work and have been tested.

### CODE REVIEW

**Comment by stdedos** [comment]
Sadly, no secrets 😅 

_I could steal your GPG key_ 😉 

If you decide, instead, to "somehow hide" this step with `${{ github.repository_owner == 'pylint-dev' && 'true' || 'false' }}`, and/or replace the GPG key for non-your-flows with a public one (i.e., `brndnmtthws-staging NOT SECURE`, stored in ENV instead) - then you could play with this.

**Comment by brndnmtthws** [comment]
> Sorry, no secrets 😅
> 
> _I could steal your GPG key_ 😉
> 
> If you decide, instead, to "somehow hide" this step with `${{ github.repository_owner == 'pylint-dev' && 'true' || 'false' }}`, and/or replace the GPG key for non-your-flows with a public one (i.e., `brndnmtthws-staging NOT SECURE`, stored in ENV instead) - then you could play with this.
> 
> OR - you could create your own branch with my commit, activate builds pushed on _that branch_, and push it yourself, i.e.
> 
> ```yaml
> on:
>   push:
>     branches:
>       - main
>       - ci/playground/*
> ```

I just updated the code to only sign the appimage on main, so it should be fine now. I need to rotate that key, too.

**Comment by stdedos** [comment]
_Ah, you did that already_ 😅 

How come "there is `clang` available"? You don't install it 😕 

Also `CC=clang CXX=clang` should've worked, probably?
Unless you want to hardcode ofc

**Comment by brndnmtthws** [comment]
> _Ah, you did that already_ 😅
> 
> How come "there is `clang` available"? You don't install it 😕
> 
> Also `CC=clang CXX=clang` should've worked, probably? Unless you want to hardcode ofc

The github runners include several versions of clang, so it's better to specify the precise version, as opposed to assuming there's a symlink. I'm not even sure if the default runners symlink `/usr/bin/clang` to anything (they probably do, for backward compat).

**Comment by stdedos** [comment]
`2.48.9-1ubuntu0.20.04.4` is "recent enough" ... no?

https://packages.ubuntu.com/search?keywords=librsvg2-dev

Package librsvg2-dev
[focal (20.04LTS)](https://packages.ubuntu.com/focal/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.48.9-1ubuntu0.20.04.4 [security]: amd64 i386
2.48.2-1 [ports]: arm64 armhf ppc64el riscv64 s390x
[focal-updates](https://packages.ubuntu.com/focal-updates/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.48.9-1ubuntu0.20.04.4: amd64 arm64 armhf i386 ppc64el riscv64 s390x
[jammy (22.04LTS)](https://packages.ubuntu.com/jammy/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.52.5+dfsg-3ubuntu0.2 [security]: amd64 i386
2.52.5+dfsg-3 [ports]: arm64 armhf ppc64el riscv64 s390x
[jammy-updates](https://packages.ubuntu.com/jammy-updates/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.52.5+dfsg-3ubuntu0.2: amd64 arm64 armhf i386 ppc64el riscv64 s390x
[lunar (23.04)](https://packages.ubuntu.com/lunar/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.54.5+dfsg-1ubuntu2.1 [security]: amd64 i386
2.54.5+dfsg-1ubuntu2 [ports]: arm64 armhf ppc64el riscv64 s390x
[lunar-updates](https://packages.ubuntu.com/lunar-updates/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.54.5+dfsg-1ubuntu2.1: amd64 arm64 armhf i386 ppc64el riscv64 s390x
[mantic (23.10)](https://packages.ubuntu.com/mantic/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.54.7+dfsg-2: amd64 arm64 armhf i386 ppc64el riscv64 s390x
[noble](https://packages.ubuntu.com/noble/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development)
2.54.7+dfsg-2: amd64 arm64 armhf i386 ppc64el riscv64 s390x

**Comment by brndnmtthws** [comment]
> `2.48.9-1ubuntu0.20.04.4` is "recent enough" ... no?
> 
> https://packages.ubuntu.com/search?keywords=librsvg2-dev
> 
> Package librsvg2-dev [focal (20.04LTS)](https://packages.ubuntu.com/focal/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.48.9-1ubuntu0.20.04.4 [security]: amd64 i386 2.48.2-1 [ports]: arm64 armhf ppc64el riscv64 s390x [focal-updates](https://packages.ubuntu.com/focal-updates/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.48.9-1ubuntu0.20.04.4: amd64 arm64 armhf i386 ppc64el riscv64 s390x [jammy (22.04LTS)](https://packages.ubuntu.com/jammy/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.52.5+dfsg-3ubuntu0.2 [security]: amd64 i386 2.52.5+dfsg-3 [ports]: arm64 armhf ppc64el riscv64 s390x [jammy-updates](https://packages.ubuntu.com/jammy-updates/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.52.5+dfsg-3ubuntu0.2: amd64 arm64 armhf i386 ppc64el riscv64 s390x [lunar (23.04)](https://packages.ubuntu.com/lunar/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.54.5+dfsg-1ubuntu2.1 [security]: amd64 i386 2.54.5+dfsg-1ubuntu2 [ports]: arm64 armhf ppc64el riscv64 s390x [lunar-updates](https://packages.ubuntu.com/lunar-updates/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.54.5+dfsg-1ubuntu2.1: amd64 arm64 armhf i386 ppc64el riscv64 s390x [mantic (23.10)](https://packages.ubuntu.com/mantic/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.54.7+dfsg-2: amd64 arm64 armhf i386 ppc64el riscv64 s390x [noble](https://packages.ubuntu.com/noble/librsvg2-dev) (libdevel): SAX-based renderer library for SVG files (development) 2.54.7+dfsg-2: amd64 arm64 armhf i386 ppc64el riscv64 s390x

There was a backward incompatible change in 2.50 I believe, and it's just too much work to try and support multiple upstream versions. There are a few places where I've made it work elsewhere, but the demand for librsvg Lua bindings is low, so I don't think it's worth the trouble. If people really want it, they can use the nix flake, or upgrade.

**Comment by stdedos** [comment]
That is a bit unfortunate 😕 

https://github.com/brndnmtthws/conky/actions/runs/8097991410/job/22130348973?pr=1761#step:6:5

```
Run echo "GIT_VERSION=$(git describe --tags --always)" | tee -a $GITHUB_ENV
  echo "GIT_VERSION=$(git describe --tags --always)" | tee -a $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
GIT_VERSION=dbb[2](https://github.com/brndnmtthws/conky/actions/runs/8097991410/job/22130348973?pr=1761#step:6:2)02fc
```

esp. because you have "some kind of merge trains" (idk GH terminology, apologies)

Otherwise, everything seems to work 🎉

**Review by brndnmtthws — APPROVED** [review]
Thanks for the PR!

**Comment by stdedos** [comment]
Thank you for the commit-fever 🙃

**Comment by stdedos** [comment]
Yea, fixed the last one too https://github.com/brndnmtthws/conky/actions/runs/8098296692/job/22131365058?pr=1761#step:5:10

**Comment by stdedos** [comment]
Ooooh nou 😅 

19 commits _just splat!_ on the `main` line 🤣 🤣 🤣 🤣

**Pull request merged**
