### PR TITLE
Fix graph leakage and the uninitialized values.

### PR DESCRIPTION
**Pull request by jbenden**

### CODE REVIEW

**Comment by Tomunu** [comment]
It looks like the memory leak is still there. It also looks like there's still the uninitialized values problem, but that might be something else. 

Here's the config I used:
(The short update time and the dozens of graphs are just to make the leak more obvious sooner.)
```
conky.config = {
-- Use double buffering (reduces flicker, may not work for everyone)
	double_buffer = true,

-- Update interval in seconds
	update_interval = 0.1,

-- Text alignment
	alignment = 'top_left',
};

conky.text = [[
 ${memgraph 20,200}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
 ${memgraph}
]];
```

**Comment by jbenden** [comment]
I threw away my fixes and imported/cleaned the patch from #856 by @SpartanJ

**Comment by Tomunu** [comment]
This seems to fix both the memory leak and the uninitialized problem. 

There's another REALLY SMALL memory leak that happens when reloading the conf file (not related to graphs) but it existed before I made the recent changes to the graphs. I only mention this here because I found it when testing for the graph memory leak.

**Comment by lasers** [comment]
Thanks Joe!

**Comment by BytEvil** [comment]
Thanks friends! ;)

**Pull request merged**
